# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chebSetN <- function(n) {
    invisible(.Call('_schrodinger_chebSetN', PACKAGE = 'schrodinger', n))
}

computeSpectrum <- function(px = numeric(), py = numeric(), nEigen = 3L, method = "cheb", dE = 0.1, tol = 1e-9) {
    .Call('_schrodinger_computeSpectrum', PACKAGE = 'schrodinger', px, py, nEigen, method, dE, tol)
}

